# Generated by Django 4.2.15 on 2026-08-06 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver", models.CharField(max_length=32, verbose_name="姓名")),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                ("province", models.CharField(max_length=10, verbose_name="省份")),
                ("city", models.CharField(max_length=10, verbose_name="城市")),
                ("district", models.CharField(max_length=10, verbose_name="区域")),
                ("detail", models.CharField(max_length=255, verbose_name="详细地址")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
