# Generated by Django 4.2.15 on 2026-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraddresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="商品名")),
                (
                    "icon",
                    models.CharField(
                        default="Grid", max_length=32, verbose_name="分类图标"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.productcategories",
                        verbose_name="父级分类",
                    ),
                ),
            ],
        ),
    ]
