# Generated by Django 4.2.15 on 2026-08-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_productcategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="商品名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="打折价格",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="商品图片"
                    ),
                ),
                (
                    "images",
                    models.TextField(
                        blank=True, default="[]", verbose_name="商品图片列表"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="商品详情"),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="")),
                ("stock", models.IntegerField(default=0, verbose_name="")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.productcategories",
                        verbose_name="所属分类",
                    ),
                ),
            ],
        ),
    ]
