# Generated by Django 4.2.15 on 2026-08-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_orders_alter_products_stock_ordersitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5, verbose_name="(1-5)星")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="评论"),
                ),
                (
                    "images",
                    models.TextField(blank=True, default="[]", verbose_name="评价图片"),
                ),
                (
                    "reply",
                    models.TextField(blank=True, default="", verbose_name="商家回复"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.orders",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.products",
                        verbose_name="评价商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评价用户",
                    ),
                ),
            ],
        ),
    ]
