# Generated by Django 4.2.15 on 2026-08-21 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="商家",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "普通用户"),
                    ("merchant", "商家"),
                    ("admin", "管理员"),
                    ("superadmin", "超级管理员"),
                ],
                default="user",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
