# Generated by Django 4.2.15 on 2026-08-22 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_products_merchant_userinfo_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="complete_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AddField(
            model_name="orders",
            name="is_reviewed",
            field=models.BooleanField(default=False, verbose_name="是否已评价"),
        ),
        migrations.AddField(
            model_name="orders",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="商家",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="ship_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发货时间"),
        ),
        migrations.AddField(
            model_name="useraddresses",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="是否默认"),
        ),
    ]
