# Generated by Django 4.2.15 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_orders_complete_time_orders_is_reviewed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="pay_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
    ]
