# Generated by Django 4.2.15 on 2026-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_orders_pay_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="audit_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "审核通过"),
                    ("rejected", "审核拒绝"),
                ],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="reject_reason",
            field=models.TextField(blank=True, default="", verbose_name="拒绝原因"),
        ),
        migrations.AlterField(
            model_name="products",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="是否上架"),
        ),
    ]
