# Generated by Django 4.2.15 on 2026-08-28 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_products_audit_status_products_reject_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
    ]
