# Generated by Django 4.2.15 on 2026-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userinfo_created_at_userinfo_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="created_at",
            new_name="create_time",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="created_at",
            new_name="create_time",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="created_at",
            new_name="create_time",
        ),
    ]
