# Generated by Django 4.2.15 on 2026-08-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_created_at_cartitem_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="头像"
            ),
        ),
    ]
