# Generated by Django 4.2.15 on 2026-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_userinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_no",
            field=models.CharField(max_length=32, unique=True, verbose_name="订单号"),
        ),
        migrations.AlterField(
            model_name="products",
            name="sales",
            field=models.IntegerField(default=0, verbose_name="销量"),
        ),
    ]
