"""
Django settings for practice project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load private local configuration; existing environment variables take priority.
load_dotenv(BASE_DIR.parent / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY or SECRET_KEY == 'replace-with-a-new-random-secret-key':
    raise ImproperlyConfigured(
        '请在项目根目录的 .env 或环境变量中配置新的 DJANGO_SECRET_KEY。'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",           Django 自带的后台管理界面
    "django.contrib.auth",              #用户认证系统（User 模型、登录、权限、组）
    "django.contrib.contenttypes",      #内容类型框架，记录每个 app 有哪些 Model
    "django.contrib.sessions",          #Session 框架，负责用户登录状态的持久化
    # "django.contrib.messages",        消息框架，用于在页面间传递一次性提示（如"保存成功"）
    "django.contrib.staticfiles",
    # "app01",           ← 已迁移到 apps.users，不再需要
    "rest_framework",
    "apps.users",       # 用户模块
    # 后面加 ↓
    # "apps.products",  # 商品模块
    # "apps.orders",    # 订单模块
    # "apps.cart",      # 购物车
    # "apps.reviews",   # 评价
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",    # 在每个请求上挂载 request.user，实现用户识别
    # "django.contrib.messages.middleware.MessageMiddleware",       支持基于 cookie/session 的闪存消息
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "practice.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",            在模板中提供 user / perms 变量
                # "django.contrib.messages.context_processors.messages",    在模板中提供 messages 变量
            ],
        },
    },
]

WSGI_APPLICATION = "practice.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "mall"),
        "USER": os.environ.get("DB_USER", "mall_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",                    # 必须，否则中文/emoji 乱码
        },
    }
}
# Redis 缓存配置（django-redis 后端）
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",    # Redis 作为 Django 缓存后端
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "KEY_PREFIX": os.environ.get("REDIS_KEY_PREFIX", "mall"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.environ.get("REDIS_PASSWORD", ""),
            "SERIALIZER": "apps.common.redis_serializer.UTF8JSONSerializer",  # 中文直读，不转 \u
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
        # 告诉 DRF：每个请求都用 JWT 验证身份
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 告诉 DRF：必须登录（有有效 token）才能访问
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 全局分页配置（加这两行）
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardPagination',
    'PAGE_SIZE': 10,  # 默认每页10条
    # 全局异常处理器：统一错误格式为 {code, message, data}
    'EXCEPTION_HANDLER': 'apps.common.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  #access token 30分钟过期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     #refresh token 1天过期
}
# 不使用Django内置的user表，用自己自定义的User表
AUTH_USER_MODEL = 'users.UserInfo'

MEDIA_URL = "/media/"  # 上传文件的 URL 前缀
MEDIA_ROOT = BASE_DIR / "media"  # 上传文件保存在当前项目目录